import "./globals.css";
import Navbar from "@/lib/components/Navbar";

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="emerald">
      <head>
        <title>Rtrade</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
